// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhaTre.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NhaTre.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915110427_AddHealthMoodAndTemperature_RestrictPickupPerson")]
    partial class AddHealthMoodAndTemperature_RestrictPickupPerson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NhaTre.Domain.Entities.ActivityPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<string>("FileReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_reference");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_teacher_id");

                    b.HasKey("Id")
                        .HasName("pk_activity_photos");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_activity_photos_class_id");

                    b.HasIndex("UploadedByTeacherId")
                        .HasDatabaseName("ix_activity_photos_uploaded_by_teacher_id");

                    b.ToTable("activity_photos", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<Guid>("RecordedByTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_teacher_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_attendances");

                    b.HasIndex("RecordedByTeacherId")
                        .HasDatabaseName("ix_attendances_recorded_by_teacher_id");

                    b.HasIndex("ChildId", "AttendanceDate")
                        .IsUnique()
                        .HasDatabaseName("ix_attendances_child_id_attendance_date");

                    b.ToTable("attendances", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("date")
                        .HasColumnName("enrollment_date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_children");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_children_class_id");

                    b.ToTable("children", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.ChildGuardian", b =>
                {
                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<Guid>("GuardianUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("guardian_user_id");

                    b.HasKey("ChildId", "GuardianUserId")
                        .HasName("pk_child_guardians");

                    b.HasIndex("GuardianUserId")
                        .HasDatabaseName("ix_child_guardians_guardian_user_id");

                    b.ToTable("child_guardians", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("HomeroomTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("homeroom_teacher_id");

                    b.Property<int?>("MaxAgeMonths")
                        .HasColumnType("integer")
                        .HasColumnName("max_age_months");

                    b.Property<int?>("MinAgeMonths")
                        .HasColumnType("integer")
                        .HasColumnName("min_age_months");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("HomeroomTeacherId")
                        .HasDatabaseName("ix_classes_homeroom_teacher_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_name");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.GrowthMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("height_cm");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_growth_measurements");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_growth_measurements_child_id");

                    b.HasIndex("RecordedByUserId")
                        .HasDatabaseName("ix_growth_measurements_recorded_by_user_id");

                    b.ToTable("growth_measurements", null, t =>
                        {
                            t.HasCheckConstraint("CK_GrowthMeasurement_HeightOrWeight", "height_cm IS NOT NULL OR weight_kg IS NOT NULL");
                        });
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("RecordedByTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_teacher_id");

                    b.HasKey("Id")
                        .HasName("pk_incidents");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_incidents_child_id");

                    b.HasIndex("RecordedByTeacherId")
                        .HasDatabaseName("ix_incidents_recorded_by_teacher_id");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.IncidentPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_reference");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.HasKey("Id")
                        .HasName("pk_incident_photos");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_incident_photos_incident_id");

                    b.ToTable("incident_photos", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TuitionFeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("tuition_fee_id");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_invoices_child_id");

                    b.HasIndex("TuitionFeeId")
                        .HasDatabaseName("ix_invoices_tuition_fee_id");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_Invoice_AmountPositive", "amount > 0");

                            t.HasCheckConstraint("CK_Invoice_Status", "status IN ('unpaid', 'paid')");
                        });
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.MenuEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("WeeklyMenuId")
                        .HasColumnType("uuid")
                        .HasColumnName("weekly_menu_id");

                    b.HasKey("Id")
                        .HasName("pk_menu_entries");

                    b.HasIndex("WeeklyMenuId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_menu_entries_weekly_menu_id_day_of_week");

                    b.ToTable("menu_entries", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("RecipientUserId")
                        .HasDatabaseName("ix_notifications_recipient_user_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_payments_invoice_id");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payment_AmountPositive", "amount > 0");
                        });
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Pickup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttendanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendance_id");

                    b.Property<Guid?>("PickupPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickup_person_id");

                    b.Property<DateTime>("PickupTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pickup_time");

                    b.Property<Guid>("RecordedByTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_teacher_id");

                    b.HasKey("Id")
                        .HasName("pk_pickups");

                    b.HasIndex("AttendanceId")
                        .IsUnique()
                        .HasDatabaseName("ix_pickups_attendance_id");

                    b.HasIndex("PickupPersonId")
                        .HasDatabaseName("ix_pickups_pickup_person_id");

                    b.HasIndex("RecordedByTeacherId")
                        .HasDatabaseName("ix_pickups_recorded_by_teacher_id");

                    b.ToTable("pickups", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.QuickHealthStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mood");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("RecordedByTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by_teacher_id");

                    b.Property<decimal?>("TemperatureCelsius")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperature_celsius");

                    b.HasKey("Id")
                        .HasName("pk_quick_health_statuses");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_quick_health_statuses_child_id");

                    b.HasIndex("RecordedByTeacherId")
                        .HasDatabaseName("ix_quick_health_statuses_recorded_by_teacher_id");

                    b.ToTable("quick_health_statuses", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.RegisteredPickupPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_registered_pickup_persons");

                    b.HasIndex("ChildId")
                        .HasDatabaseName("ix_registered_pickup_persons_child_id");

                    b.ToTable("registered_pickup_persons", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Role", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Giáo viên"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Kế toán/Văn phòng"
                        },
                        new
                        {
                            Id = (short)4,
                            Name = "Y tế"
                        },
                        new
                        {
                            Id = (short)5,
                            Name = "Phụ huynh"
                        });
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_teachers");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_teachers_user_id");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.TuitionFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id")
                        .HasName("pk_tuition_fees");

                    b.ToTable("tuition_fees", null, t =>
                        {
                            t.HasCheckConstraint("CK_TuitionFee_AmountPositive", "amount > 0");
                        });
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("credential_reference");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LoginIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login_identifier");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("LoginIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_users_login_identifier");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.WeeklyMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date")
                        .HasColumnName("week_start_date");

                    b.HasKey("Id")
                        .HasName("pk_weekly_menus");

                    b.HasIndex("WeekStartDate")
                        .IsUnique()
                        .HasDatabaseName("ix_weekly_menus_week_start_date");

                    b.ToTable("weekly_menus", (string)null);
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.ActivityPhoto", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Class", "Class")
                        .WithMany("ActivityPhotos")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_photos_classes_class_id");

                    b.HasOne("NhaTre.Domain.Entities.Teacher", "UploadedByTeacher")
                        .WithMany("ActivityPhotos")
                        .HasForeignKey("UploadedByTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_activity_photos_teachers_uploaded_by_teacher_id");

                    b.Navigation("Class");

                    b.Navigation("UploadedByTeacher");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Attendance", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Child", "Child")
                        .WithMany("Attendances")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendances_children_child_id");

                    b.HasOne("NhaTre.Domain.Entities.Teacher", "RecordedByTeacher")
                        .WithMany("Attendances")
                        .HasForeignKey("RecordedByTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendances_teachers_recorded_by_teacher_id");

                    b.Navigation("Child");

                    b.Navigation("RecordedByTeacher");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Child", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Class", "Class")
                        .WithMany("Children")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("fk_children_classes_class_id");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.ChildGuardian", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Child", "Child")
                        .WithMany("ChildGuardians")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_child_guardians_children_child_id");

                    b.HasOne("NhaTre.Domain.Entities.User", "GuardianUser")
                        .WithMany("ChildGuardians")
                        .HasForeignKey("GuardianUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_child_guardians_users_guardian_user_id");

                    b.Navigation("Child");

                    b.Navigation("GuardianUser");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Class", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Teacher", "HomeroomTeacher")
                        .WithMany("HomeroomClasses")
                        .HasForeignKey("HomeroomTeacherId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_classes_teachers_homeroom_teacher_id");

                    b.Navigation("HomeroomTeacher");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.GrowthMeasurement", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Child", "Child")
                        .WithMany("GrowthMeasurements")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_growth_measurements_children_child_id");

                    b.HasOne("NhaTre.Domain.Entities.User", "RecordedByUser")
                        .WithMany("GrowthMeasurements")
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_growth_measurements_users_recorded_by_user_id");

                    b.Navigation("Child");

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Incident", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Child", "Child")
                        .WithMany("Incidents")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_children_child_id");

                    b.HasOne("NhaTre.Domain.Entities.Teacher", "RecordedByTeacher")
                        .WithMany("Incidents")
                        .HasForeignKey("RecordedByTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_teachers_recorded_by_teacher_id");

                    b.Navigation("Child");

                    b.Navigation("RecordedByTeacher");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.IncidentPhoto", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Incident", "Incident")
                        .WithMany("IncidentPhotos")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incident_photos_incidents_incident_id");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Child", "Child")
                        .WithMany("Invoices")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_children_child_id");

                    b.HasOne("NhaTre.Domain.Entities.TuitionFee", "TuitionFee")
                        .WithMany("Invoices")
                        .HasForeignKey("TuitionFeeId")
                        .HasConstraintName("fk_invoices_tuition_fees_tuition_fee_id");

                    b.Navigation("Child");

                    b.Navigation("TuitionFee");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.MenuEntry", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.WeeklyMenu", "WeeklyMenu")
                        .WithMany("MenuEntries")
                        .HasForeignKey("WeeklyMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_entries_weekly_menus_weekly_menu_id");

                    b.Navigation("WeeklyMenu");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Notification", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.User", "RecipientUser")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_recipient_user_id");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Payment", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Pickup", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Attendance", "Attendance")
                        .WithOne("Pickup")
                        .HasForeignKey("NhaTre.Domain.Entities.Pickup", "AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pickups_attendances_attendance_id");

                    b.HasOne("NhaTre.Domain.Entities.RegisteredPickupPerson", "PickupPerson")
                        .WithMany("Pickups")
                        .HasForeignKey("PickupPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pickups_registered_pickup_persons_pickup_person_id");

                    b.HasOne("NhaTre.Domain.Entities.Teacher", "RecordedByTeacher")
                        .WithMany("Pickups")
                        .HasForeignKey("RecordedByTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pickups_teachers_recorded_by_teacher_id");

                    b.Navigation("Attendance");

                    b.Navigation("PickupPerson");

                    b.Navigation("RecordedByTeacher");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.QuickHealthStatus", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Child", "Child")
                        .WithMany("QuickHealthStatuses")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quick_health_statuses_children_child_id");

                    b.HasOne("NhaTre.Domain.Entities.Teacher", "RecordedByTeacher")
                        .WithMany("QuickHealthStatuses")
                        .HasForeignKey("RecordedByTeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quick_health_statuses_teachers_recorded_by_teacher_id");

                    b.Navigation("Child");

                    b.Navigation("RecordedByTeacher");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.RegisteredPickupPerson", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Child", "Child")
                        .WithMany("RegisteredPickupPersons")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registered_pickup_persons_children_child_id");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Teacher", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("NhaTre.Domain.Entities.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.User", b =>
                {
                    b.HasOne("NhaTre.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Attendance", b =>
                {
                    b.Navigation("Pickup");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Child", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ChildGuardians");

                    b.Navigation("GrowthMeasurements");

                    b.Navigation("Incidents");

                    b.Navigation("Invoices");

                    b.Navigation("QuickHealthStatuses");

                    b.Navigation("RegisteredPickupPersons");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Class", b =>
                {
                    b.Navigation("ActivityPhotos");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Incident", b =>
                {
                    b.Navigation("IncidentPhotos");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.RegisteredPickupPerson", b =>
                {
                    b.Navigation("Pickups");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("ActivityPhotos");

                    b.Navigation("Attendances");

                    b.Navigation("HomeroomClasses");

                    b.Navigation("Incidents");

                    b.Navigation("Pickups");

                    b.Navigation("QuickHealthStatuses");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.TuitionFee", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.User", b =>
                {
                    b.Navigation("ChildGuardians");

                    b.Navigation("GrowthMeasurements");

                    b.Navigation("Notifications");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("NhaTre.Domain.Entities.WeeklyMenu", b =>
                {
                    b.Navigation("MenuEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
